### PR TITLE
Register ejs as .ejs handler to avoid error when monitor path requested

### PR DESCRIPTION
**Pull request by evocateur**
When cluster2 is used as a dependency by another project, accessing the monitor path elicits this error stack:

```
Error: Cannot find module 'ejs'
    at Function._resolveFilename (module.js:337:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at View.templateEngine (/[...]/node_modules/express/lib/view/view.js:134:38)
    at Function.compile (/[...]/node_modules/express/lib/view.js:68:17)
    at ServerResponse._render (/[...]/node_modules/express/lib/view.js:417:18)
    at ServerResponse.render (/[...]/node_modules/express/lib/view.js:318:17)
    at /[...]/node_modules/cluster2/lib/monitor.js:45:17
    at callbacks (/[...]/node_modules/cluster2/node_modules/express/lib/router/index.js:272:11)
```

Effectively, without the `app.register` call, node is using the current project's node_modules as it's starting point for evaluating the require path, and not the dependency's nested node_modules. I don't know why, but it's probably due to closures at some point in the stack that are preserving the modified "current working directory".

### CODE REVIEW

**Comment by strk** [comment]
I'm having this problem but your changes don't fix it here, any idea about how to debug it ?

**Comment by strk** [comment]
can it have to do with the version of express being used ?
I've a mix of 2.5.9 and 2.5.11 -- the former under cluster2, the latter one module up.

**Comment by strk** [comment]
an excerpt from my `npm ls` output:

```
windshaft-cartodb@0.1.0 /home/src/cartodb/Windshaft-cartodb
├─┬ cluster2@0.3.1 -> /home/src/cartodb/cluster2
│ ├── ejs@0.7.2 
│ ├─┬ express@2.5.9 
...
└─┬ windshaft@0.5.1 
  ├─┬ express@2.5.11 
```

No other occurrences of `ejs`

**Comment by shimonchayim** [comment]
I don't seem to see a problem now. Please feel free to open an issue if you still see the problem.

**Pull request closed without merging**
